// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBGenDevice;
@class GPBGenSettings;
@class GPBGenStatus;
@class GPBGenSystemMessage;
@class GPBGenText;
@class GPBGenVoice;


NS_ASSUME_NONNULL_BEGIN

#pragma mark - GPBGenMessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GPBGenMessageRoot : GPBRootObject
@end

#pragma mark - GPBGenMessage

typedef GPB_ENUM(GPBGenMessage_FieldNumber) {
  GPBGenMessage_FieldNumber_UserId = 1,
  GPBGenMessage_FieldNumber_MessageId = 2,
  GPBGenMessage_FieldNumber_Last = 3,
  GPBGenMessage_FieldNumber_Token = 4,
  GPBGenMessage_FieldNumber_Voice = 5,
  GPBGenMessage_FieldNumber_Text = 6,
  GPBGenMessage_FieldNumber_SystemMessage = 7,
  GPBGenMessage_FieldNumber_Device = 8,
  GPBGenMessage_FieldNumber_Settings = 9,
  GPBGenMessage_FieldNumber_Status = 10,
  GPBGenMessage_FieldNumber_UserChannel = 11,
  GPBGenMessage_FieldNumber_TtsEngine = 12,
  GPBGenMessage_FieldNumber_SttEngine = 13,
  GPBGenMessage_FieldNumber_MessageName = 14,
};


typedef GPB_ENUM(GPBGenMessage_Content_OneOfCase) {
    GPBGenMessage_Content_OneOfCase_GPBUnsetOneOfCase = 0,
    GPBGenMessage_Content_OneOfCase_Voice = 5,
    GPBGenMessage_Content_OneOfCase_Text = 6,
    GPBGenMessage_Content_OneOfCase_SystemMessage = 7,
    GPBGenMessage_Content_OneOfCase_Device = 8,
    GPBGenMessage_Content_OneOfCase_Settings = 9,
    GPBGenMessage_Content_OneOfCase_Status = 10,
};


@interface GPBGenMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userChannel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageName;

@property(nonatomic, readwrite) int64_t messageId;

/** false = -1 | 0 - undefined | true = 1 // default=false */
@property(nonatomic, readwrite) int32_t last;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite) GPBGenMessage_Content_OneOfCase contentOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) GPBGenVoice *voice;

@property(nonatomic, readwrite, copy, null_resettable) GPBGenText *text;

/** JSON as String */
@property(nonatomic, readwrite, copy, null_resettable) GPBGenSystemMessage *systemMessage;

@property(nonatomic, readwrite, copy, null_resettable) GPBGenDevice *device;

@property(nonatomic, readwrite, copy, null_resettable) GPBGenSettings *settings;

@property(nonatomic, readwrite, copy, null_resettable) GPBGenStatus *status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ttsEngine;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sttEngine;

@end

/**
 * Clears whatever value was set for the oneof 'content'.
 **/

void GPBGenMessage_ClearContentOneOfCase(GPBGenMessage *message);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
