// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Settings.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "Settings.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GPBGenSettingsRoot

@implementation GPBGenSettingsRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - GPBGenSettingsRoot_FileDescriptor

static GPBFileDescriptor *GPBGenSettingsRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"proto"
                                                 objcPrefix:@"GPBGen"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GPBGenSettings

@implementation GPBGenSettings

@dynamic echo;
@dynamic dubbing;
@dynamic ttsEngine;
@dynamic sttEngine;
@dynamic sttAutoStop;

typedef struct GPBGenSettings__storage_ {
  uint32_t _has_storage_[1];
  int32_t dubbing;
  int32_t echo;
  int32_t sttAutoStop;
  NSString *ttsEngine;
  NSString *sttEngine;
} GPBGenSettings__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "dubbing",
        .dataTypeSpecific.className = NULL,
        .number = GPBGenSettings_FieldNumber_Dubbing,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GPBGenSettings__storage_, dubbing),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "echo",
        .dataTypeSpecific.className = NULL,
        .number = GPBGenSettings_FieldNumber_Echo,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GPBGenSettings__storage_, echo),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "ttsEngine",
        .dataTypeSpecific.className = NULL,
        .number = GPBGenSettings_FieldNumber_TtsEngine,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GPBGenSettings__storage_, ttsEngine),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sttEngine",
        .dataTypeSpecific.className = NULL,
        .number = GPBGenSettings_FieldNumber_SttEngine,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GPBGenSettings__storage_, sttEngine),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sttAutoStop",
        .dataTypeSpecific.className = NULL,
        .number = GPBGenSettings_FieldNumber_SttAutoStop,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GPBGenSettings__storage_, sttAutoStop),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GPBGenSettings class]
                                     rootClass:[GPBGenSettingsRoot class]
                                          file:GPBGenSettingsRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GPBGenSettings__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
